name: Outdated package checks

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ main ]
    paths:
      - '.github/workflows/check-outdated-packages.yml'
      - 'src/**'

env:
  SOLUTION_PATH: 'src/AwsScheduleExpressionValidator.sln'
  NPM_PROJECT_DIR: 'src/AwsScheduleExpressionValidatorDemo'

jobs:
  outdated-packages-check:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - uses: trossr32/outdated-packages-action@v3.0.0
        with:
          use-dotnet-outdated: true
          dotnet-solution-or-project-path: ${{ env.SOLUTION_PATH }}
          dotnet-version: '10.*.*'
          use-npm-outdated: true
          npm-project-directory: ${{ env.NPM_PROJECT_DIR }}